// Mechanics -----------------------------------
GUIDES_AMOUNT = 18;

COUNTDOWN_DURATION = 2000;
GAME_DURATION = 10000;
KNOCKOUT_DURATION = 500;
ARENA_RADIUS = 0.9;
HOOKS_AMOUNT = 200;
BAD_HOOKS_FRQ = 5;
HOOKS_PAUSE = 1;
COMBO_DELTA = 300;
POINTS_BAD = 100;
SPECIAL_HOOK_DURATION = 9000;

// Physics -------------------------------------
PHYS_GRAVITY = 0.0;
PHYS_DRAG = 0.2;
SPRING_STRENGTH = 0.2;
SPRING_DAMPING = 0.01;

// Design --------------------------------------
CABLE_THICKNESS = 3;
HOOK_RADIUS = 8;

COLOR_PURPLE = '#B788D6';
COLOR_LIGHTGRAY = '#A7A8AC';
COLOR_BLACK = '#1A1A1A';


COLOR_RED = '#F33';
COLOR_BLUE = '#69BAFF';
COLOR_WHITE = '#FFF';
